use super::*;
use fuel_core_types::fuel_tx::consensus_parameters::gas::GasCostsValuesV6;
pub fn default_gas_costs() -> GasCostsValues {
    GasCostsValuesV6 {
        add: 2,
        addi: 2,
        and: 2,
        andi: 2,
        bal: 617,
        bhei: 2,
        bhsh: 142,
        burn: 1256,
        cb: 2,
        cfsi: 2,
        div: 2,
        divi: 2,
        eck1: 3429,
        ecr1: 45170,
        eq: 2,
        exp: 2,
        expi: 2,
        flag: 2,
        gm: 2,
        gt: 2,
        gtf: 3,
        ji: 2,
        jmp: 2,
        jne: 2,
        jnei: 2,
        jnzi: 2,
        jmpf: 2,
        jmpb: 2,
        jnzf: 2,
        jnzb: 2,
        jnef: 2,
        jneb: 2,
        lb: 2,
        log: 189,
        lt: 2,
        lw: 2,
        mint: 426,
        mlog: 2,
        vm_initialization: DependentCost::LightOperation {
            base: 7098,
            units_per_gas: 27,
        },
        modi: 2,
        mod_op: 2,
        movi: 2,
        mroo: 5,
        mul: 2,
        muli: 2,
        mldv: 4,
        niop: 2,
        noop: 1,
        not: 2,
        or: 2,
        ori: 2,
        poph: 5,
        popl: 5,
        pshh: 5,
        pshl: 5,
        move_op: 2,
        ret: 95,
        sb: 2,
        sll: 2,
        slli: 2,
        srl: 2,
        srli: 2,
        srw: 488,
        sub: 2,
        subi: 2,
        sw: 2,
        sww: 44,
        time: 64,
        tr: 1252,
        tro: 1254,
        wdcm: 3,
        wqcm: 3,
        wdop: 3,
        wqop: 4,
        wdml: 3,
        wqml: 4,
        wddv: 5,
        wqdv: 7,
        wdmd: 11,
        wqmd: 18,
        wdam: 10,
        wqam: 12,
        wdmm: 11,
        wqmm: 11,
        xor: 2,
        xori: 2,
        ecop: 12961,
        aloc: DependentCost::LightOperation {
            base: 2,
            units_per_gas: 301,
        },
        bsiz: DependentCost::LightOperation {
            base: 41,
            units_per_gas: 256,
        },
        bldd: DependentCost::LightOperation {
            base: 60,
            units_per_gas: 93,
        },
        cfe: DependentCost::LightOperation {
            base: 2,
            units_per_gas: 288,
        },
        cfei: DependentCost::LightOperation {
            base: 2,
            units_per_gas: 441,
        },
        call: DependentCost::LightOperation {
            base: 1199,
            units_per_gas: 45,
        },
        ccp: DependentCost::LightOperation {
            base: 107,
            units_per_gas: 101,
        },
        croo: DependentCost::LightOperation {
            base: 144,
            units_per_gas: 2,
        },
        csiz: DependentCost::LightOperation {
            base: 41,
            units_per_gas: 278,
        },
        ed19: DependentCost::LightOperation {
            base: 7389,
            units_per_gas: 3,
        },
        k256: DependentCost::LightOperation {
            base: 318,
            units_per_gas: 3,
        },
        ldc: DependentCost::LightOperation {
            base: 116,
            units_per_gas: 92,
        },
        logd: DependentCost::LightOperation {
            base: 664,
            units_per_gas: 2,
        },
        mcl: DependentCost::LightOperation {
            base: 3,
            units_per_gas: 623,
        },
        mcli: DependentCost::LightOperation {
            base: 3,
            units_per_gas: 625,
        },
        mcp: DependentCost::LightOperation {
            base: 4,
            units_per_gas: 543,
        },
        mcpi: DependentCost::LightOperation {
            base: 5,
            units_per_gas: 819,
        },
        meq: DependentCost::LightOperation {
            base: 3,
            units_per_gas: 608,
        },
        rvrt: 107,
        s256: DependentCost::LightOperation {
            base: 52,
            units_per_gas: 2,
        },
        scwq: DependentCost::HeavyOperation {
            base: 497,
            gas_per_unit: 508,
        },
        smo: DependentCost::LightOperation {
            base: 5071,
            units_per_gas: 2,
        },
        srwq: DependentCost::HeavyOperation {
            base: 510,
            gas_per_unit: 509,
        },
        swwq: DependentCost::HeavyOperation {
            base: 46,
            gas_per_unit: 63,
        },
        epar: DependentCost::HeavyOperation {
            base: 189059,
            gas_per_unit: 138176,
        },
        contract_root: DependentCost::LightOperation {
            base: 53,
            units_per_gas: 1,
        },
        state_root: DependentCost::HeavyOperation {
            base: 414,
            gas_per_unit: 209,
        },
        new_storage_per_byte: 63,
        retd: DependentCost::LightOperation {
            base: 511,
            units_per_gas: 2,
        },
    }
    .into()
}
