use super::*;
use fuel_core_types::fuel_tx::consensus_parameters::gas::GasCostsValuesV6;
pub fn default_gas_costs() -> GasCostsValues {
    GasCostsValuesV6 {
        add: 2,
        addi: 2,
        and: 2,
        andi: 2,
        bal: 598,
        bhei: 2,
        bhsh: 132,
        burn: 1228,
        cb: 2,
        cfsi: 2,
        div: 2,
        divi: 2,
        eck1: 3424,
        ecr1: 45146,
        eq: 2,
        exp: 2,
        expi: 2,
        flag: 2,
        gm: 2,
        gt: 2,
        gtf: 3,
        ji: 2,
        jmp: 2,
        jne: 2,
        jnei: 2,
        jnzi: 2,
        jmpf: 2,
        jmpb: 2,
        jnzf: 2,
        jnzb: 2,
        jnef: 2,
        jneb: 2,
        lb: 2,
        log: 182,
        lt: 2,
        lw: 2,
        mint: 1886,
        mlog: 2,
        vm_initialization: DependentCost::LightOperation {
            base: 6928,
            units_per_gas: 27,
        },
        modi: 2,
        mod_op: 2,
        movi: 2,
        mroo: 5,
        mul: 2,
        muli: 2,
        mldv: 4,
        niop: 2,
        noop: 1,
        not: 2,
        or: 2,
        ori: 2,
        poph: 5,
        popl: 5,
        pshh: 5,
        pshl: 5,
        move_op: 2,
        ret: 105,
        sb: 2,
        sll: 2,
        slli: 2,
        srl: 2,
        srli: 2,
        srw: 503,
        sub: 2,
        subi: 2,
        sw: 2,
        sww: 510,
        time: 62,
        tr: 1642,
        tro: 1339,
        wdcm: 3,
        wqcm: 3,
        wdop: 3,
        wqop: 4,
        wdml: 4,
        wqml: 4,
        wddv: 5,
        wqdv: 7,
        wdmd: 11,
        wqmd: 18,
        wdam: 10,
        wqam: 12,
        wdmm: 11,
        wqmm: 11,
        xor: 2,
        xori: 2,
        ecop: 12911,
        aloc: DependentCost::LightOperation {
            base: 2,
            units_per_gas: 300,
        },
        bsiz: DependentCost::LightOperation {
            base: 41,
            units_per_gas: 279,
        },
        bldd: DependentCost::LightOperation {
            base: 60,
            units_per_gas: 96,
        },
        cfe: DependentCost::LightOperation {
            base: 2,
            units_per_gas: 287,
        },
        cfei: DependentCost::LightOperation {
            base: 2,
            units_per_gas: 459,
        },
        call: DependentCost::LightOperation {
            base: 1244,
            units_per_gas: 43,
        },
        ccp: DependentCost::LightOperation {
            base: 108,
            units_per_gas: 102,
        },
        croo: DependentCost::LightOperation {
            base: 136,
            units_per_gas: 2,
        },
        csiz: DependentCost::LightOperation {
            base: 46,
            units_per_gas: 274,
        },
        ed19: DependentCost::LightOperation {
            base: 7430,
            units_per_gas: 3,
        },
        k256: DependentCost::LightOperation {
            base: 319,
            units_per_gas: 3,
        },
        ldc: DependentCost::LightOperation {
            base: 125,
            units_per_gas: 92,
        },
        logd: DependentCost::LightOperation {
            base: 642,
            units_per_gas: 2,
        },
        mcl: DependentCost::LightOperation {
            base: 3,
            units_per_gas: 625,
        },
        mcli: DependentCost::LightOperation {
            base: 3,
            units_per_gas: 625,
        },
        mcp: DependentCost::LightOperation {
            base: 4,
            units_per_gas: 493,
        },
        mcpi: DependentCost::LightOperation {
            base: 5,
            units_per_gas: 819,
        },
        meq: DependentCost::LightOperation {
            base: 3,
            units_per_gas: 608,
        },
        rvrt: 98,
        s256: DependentCost::LightOperation {
            base: 52,
            units_per_gas: 2,
        },
        scwq: DependentCost::HeavyOperation {
            base: 507,
            gas_per_unit: 515,
        },
        smo: DependentCost::LightOperation {
            base: 4955,
            units_per_gas: 2,
        },
        srwq: DependentCost::HeavyOperation {
            base: 520,
            gas_per_unit: 522,
        },
        swwq: DependentCost::HeavyOperation {
            base: 507,
            gas_per_unit: 525,
        },
        epar: DependentCost::HeavyOperation {
            base: 188912,
            gas_per_unit: 138413,
        },
        contract_root: DependentCost::LightOperation {
            base: 53,
            units_per_gas: 1,
        },
        state_root: DependentCost::HeavyOperation {
            base: 414,
            gas_per_unit: 209,
        },
        new_storage_per_byte: 63,
        retd: DependentCost::LightOperation {
            base: 514,
            units_per_gas: 2,
        },
    }
    .into()
}
