use super::*;
pub fn default_gas_costs() -> GasCostsValues {
    GasCostsValues {
        add: 1,
        addi: 1,
        aloc: 1,
        and: 1,
        andi: 1,
        bal: 26,
        bhei: 1,
        bhsh: 1,
        burn: 27286,
        cb: 1,
        cfei: 1,
        cfsi: 1,
        croo: 37,
        div: 1,
        divi: 1,
        eck1: 3351,
        ecr1: 46061,
        ed19: 3163,
        eq: 1,
        exp: 1,
        expi: 1,
        flag: 1,
        gm: 1,
        gt: 1,
        gtf: 1,
        ji: 1,
        jmp: 1,
        jne: 1,
        jnei: 1,
        jnzi: 1,
        jmpf: 1,
        jmpb: 1,
        jnzf: 1,
        jnzb: 1,
        jnef: 1,
        jneb: 1,
        lb: 1,
        log: 92,
        lt: 1,
        lw: 1,
        mint: 25370,
        mlog: 1,
        vm_initialization: 1,
        modi: 1,
        mod_op: 1,
        movi: 1,
        mroo: 4,
        mul: 1,
        muli: 1,
        mldv: 3,
        noop: 1,
        not: 1,
        or: 1,
        ori: 1,
        poph: 1,
        popl: 1,
        pshh: 1,
        pshl: 1,
        move_op: 1,
        ret: 135,
        sb: 1,
        sll: 1,
        slli: 1,
        srl: 1,
        srli: 1,
        srw: 237,
        sub: 1,
        subi: 1,
        sw: 1,
        sww: 27313,
        time: 1,
        tr: 38459,
        tro: 26269,
        wdcm: 1,
        wqcm: 2,
        wdop: 2,
        wqop: 2,
        wdml: 2,
        wqml: 3,
        wddv: 4,
        wqdv: 6,
        wdmd: 10,
        wqmd: 16,
        wdam: 8,
        wqam: 10,
        wdmm: 9,
        wqmm: 9,
        xor: 1,
        xori: 1,
        call: DependentCost::LightOperation {
            base: 1171,
            units_per_gas: 47,
        },
        ccp: DependentCost::LightOperation {
            base: 39,
            units_per_gas: 65,
        },
        csiz: DependentCost::LightOperation {
            base: 49,
            units_per_gas: 214,
        },
        k256: DependentCost::LightOperation {
            base: 277,
            units_per_gas: 3,
        },
        ldc: DependentCost::LightOperation {
            base: 37,
            units_per_gas: 63,
        },
        logd: DependentCost::LightOperation {
            base: 444,
            units_per_gas: 3,
        },
        mcl: DependentCost::LightOperation {
            base: 1,
            units_per_gas: 500,
        },
        mcli: DependentCost::LightOperation {
            base: 1,
            units_per_gas: 500,
        },
        mcp: DependentCost::LightOperation {
            base: 2,
            units_per_gas: 493,
        },
        mcpi: DependentCost::LightOperation {
            base: 4,
            units_per_gas: 1023,
        },
        meq: DependentCost::LightOperation {
            base: 2,
            units_per_gas: 1111,
        },
        rvrt: 136,
        s256: DependentCost::LightOperation {
            base: 44,
            units_per_gas: 3,
        },
        scwq: DependentCost::HeavyOperation {
            base: 28687,
            gas_per_unit: 27036,
        },
        smo: DependentCost::LightOperation {
            base: 58089,
            units_per_gas: 1,
        },
        srwq: DependentCost::LightOperation {
            base: 121,
            units_per_gas: 1,
        },
        swwq: DependentCost::HeavyOperation {
            base: 26790,
            gas_per_unit: 25451,
        },
        contract_root: DependentCost::LightOperation {
            base: 44,
            units_per_gas: 2,
        },
        state_root: DependentCost::HeavyOperation {
            base: 347,
            gas_per_unit: 176,
        },
        new_storage_per_byte: 1,
        retd: DependentCost::LightOperation {
            base: 466,
            units_per_gas: 3,
        },
    }
}
