pragma solidity ^0.6.8;


enum Opcode {
    OP_STOP,
    OP_ADD,
    OP_SUB,
    OP_MUL,
    OP_DIV,
    OP_SDIV,
    OP_MOD,
    OP_SMOD,
    OP_ADDMOD,
    OP_MULMOD,
    OP_EXP,
    OP_SIGNEXTEND,
    OP_EQ,
    OP_LT,
    OP_GT,
    OP_SLT,
    OP_SGT,
    OP_ISZERO,
    OP_AND,
    OP_OR,
    OP_XOR,
    OP_NOT,
    OP_BYTE,
    OP_SHL,
    OP_SHR,
    OP_SAR,
    OP_KECCAK,
    OP_GAS,
    OP_BALANCE,
    OP_ADDRESS,
    OP_ORIGIN,
    OP_CALLER,
    OP_CALLVALUE,
    OP_CALLDATALOD,
    OP_CALLDATASIZE,
    OP_CALLDATACOPY,
    OP_CODESIZE,
    OP_CODECOPY,
    OP_GASPRICE,
    OP_EXTCODESIZE,
    OP_EXTCODECOPY,
    OP_RETURNDATASIZE,
    OP_RETURNDATACOPY,
    OP_EXTCODEHASH,
    OP_BLOCKHASH,
    OP_COINBASE,
    OP_TIMESTAMP,
    OP_NUMBER,
    OP_DIFFICULTY,
    OP_GASLIMIT,
    OP_MLOAD,
    OP_MSTORE,
    OP_MSTORE8,
    OP_SLOAD,
    OP_SSTORE,
    OP_MSIZE,
    OP_JUMP,
    OP_JUMPI,
    OP_PC,
    OP_JUMPDEST,
    OP_LOG0,
    OP_LOG1,
    OP_LOG2,
    OP_LOG3,
    OP_LOG4,
    OP_CREATE,
    OP_CALL,
    OP_CALLCODE,
    OP_RETURN,
    OP_DELEGATECALL,
    OP_CREATE2,
    OP_STATICCALL,
    OP_REVERT,
    OP_INVALID,
    OP_SELFDESTRUCT,
    OP_POP,
    OP_PUSH,
    OP_DUP,
    OP_SWAP,

    OP_VERIFY_MERKLE_PROOF,
    OP_CHECK_TEMPLATE_VERIFY, // also known as CheckOutputVerify
    OP_EXECUTE_ETH_SMART_CONTRACT,

    OP_INC,
    OP_DEC
}

enum interpret_result {
    SUCCESS,
    STOPPED,
    ERROR_TEMPLATE_FAILURE, // applies only to OP_CHECK_TEMPLATE_VERIFY
    ERROR_UNKNOWN_OPCODE // will often never apply when enum used to populate bytecode
}
