FROM ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main

RUN yum -y update && \
    yum -y install centos-release-scl && \
    yum-config-manager --enable rhel-server-rhscl-7-rpms && \
    yum -y install llvm-toolset-7.0 && \
    scl enable llvm-toolset-7.0 bash
