FROM ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main@sha256:b4f5bf74812f9bb6516140d4b83d1f173c2d5ce0523f3e1c2253d99d851c734f

RUN apt-get update && \
    apt-get install --assume-yes clang libclang-dev
