FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main@sha256:9e5b39c09874bc1816c675ed11afca2c2ed6cee0c4ed2b3c1d5763c346c9ae3f

ENV PKG_CONFIG_ALLOW_CROSS="true"

RUN dpkg --add-architecture arm64 && \
    apt-get update && \
    apt-get install --assume-yes clang-8 libclang-8-dev binutils-aarch64-linux-gnu zlib1g-dev:arm64 gcc-12 && \
    ln -s -f /usr/bin/gcc-12 /usr/bin/gcc
