FROM ubuntu:24.04

ENV PKG_CONFIG_ALLOW_CROSS="true"

RUN dpkg --add-architecture arm64 && \
    apt-get update && \
    apt-get install --assume-yes clang-8 libclang-8-dev binutils-aarch64-linux-gnu zlib1g-dev:arm64 gcc-12 && \
    ln -s -f /usr/bin/gcc-12 /usr/bin/gcc
